"""empty message

Revision ID: 054954c65e05
Revises: 5a355038d89c
Create Date: 2021-03-02 22:56:05.498410

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '054954c65e05'
down_revision = '5a355038d89c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('planetas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('climate', sa.String(length=200), nullable=False),
    sa.Column('population', sa.Integer(), nullable=False),
    sa.Column('gravity', sa.Integer(), nullable=False),
    sa.Column('orbital_period', sa.Integer(), nullable=False),
    sa.Column('diameter', sa.String(length=200), nullable=False),
    sa.Column('rotation_period', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('personajes', sa.Column('color_eyes', sa.String(length=200), nullable=False))
    op.add_column('personajes', sa.Column('color_hair', sa.String(length=200), nullable=False))
    op.alter_column('personajes', 'gender',
               existing_type=mysql.VARCHAR(length=200),
               nullable=False)
    op.drop_column('personajes', 'birthyear')
    op.drop_column('personajes', 'estatura')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('personajes', sa.Column('estatura', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('personajes', sa.Column('birthyear', mysql.VARCHAR(length=200), nullable=False))
    op.alter_column('personajes', 'gender',
               existing_type=mysql.VARCHAR(length=200),
               nullable=True)
    op.drop_column('personajes', 'color_hair')
    op.drop_column('personajes', 'color_eyes')
    op.drop_table('planetas')
    # ### end Alembic commands ###
