"""empty message

Revision ID: 5a355038d89c
Revises: 762402052503
Create Date: 2021-03-02 21:02:01.241620

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a355038d89c'
down_revision = '762402052503'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('personajes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('estatura', sa.String(length=200), nullable=True),
    sa.Column('birthyear', sa.String(length=200), nullable=False),
    sa.Column('gender', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('user', sa.Column('genero', sa.String(length=80), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'genero')
    op.drop_table('personajes')
    # ### end Alembic commands ###
